expose api to let user control log output
ggerganov/whisper.cpp pull request #1060
Opened 2023-06-28 01:48 UTC by evmar

Add
  whisper_set_log_callback()
that lets user set a callback for log messages.

Change all the
  fprintf(stderr, ...)
to call via the above.

2023-06-28 01:50 UTC, evmar commented
Note: I also considered making a log macro that included the `__func__` bit automatically, lemme know if you think that's a good idea.  Also if it's literally named `log` then it shadows `std::log` the math function so it would need a different name.

2023-07-04 12:28 UTC, ggerganov requested changes

2023-07-04 12:28 UTC, ggerganov commented on whisper.cpp
> +    char buf[256];
```suggestion
    char buf[1024];
```

2023-07-04 12:28 UTC, ggerganov commented on whisper.cpp
> +    fprintf(stderr, "%s\n", text);
New lines must be explicitly logged

```suggestion
    fprintf(stderr, "%s", text);
```

2023-07-04 12:28 UTC, ggerganov commented on whisper.cpp
> +    whisper_log(buf);
Check if `whisper_log` is `nullptr`. If it is - do nothing

2023-07-05 20:03 UTC, evmar commented
OK, I applied your suggestions and rebased.

2023-07-25 15:58 UTC, merged