Add precalculated values of sin/cos for speeding up FFT
ggerganov/whisper.cpp pull request #1142
Opened 2023-07-30 13:50 UTC by AlexandrGraschenkov

The code works in the same way as before, except that we don't spend time on sin/cos calculations. This is a real bottleneck for FFT calculations.

System info:
```
Apple M1 Pro, Mac OS Ventura 13.3
n_threads = 4 / 10 | AVX = 0 | AVX2 = 0 | AVX512 = 0 | FMA = 0 | NEON = 1 | ARM_FMA = 1 | F16C = 0 | FP16_VA = 1 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 0 | VSX = 0 | COREML = 0 | OPENVINO = 0 |
```

Testing on: `./main -f samples/a13.wav`
| Version | mel time |
| --- | -- |
| Original | 55.17 ms |
| Cos/sin table | **19.15 ms** |

Testing on:  `./main -f samples/diffusion2023-07-03.wav`
| Version | mel time | 
| --- | -- |
| Original | 2142.07 ms |
| Cos/sin table | **734.42 ms** |

2023-08-01 03:22 UTC, bobqianic approved these changes

2023-08-03 18:19 UTC, bobqianic commented
@AlexandrGraschenkov If you have some free time, could you do me a favor and test how much of an improvement there would be if the optimization in #1148 is combined with your optimization? This is because I've set it to skip FFT calculations and output the results directly when the FFT input is all zeros during the calculation of log Mel. If you have more time, please help me see how much the quality of speech-to-text has improved. Thank you!

2023-08-25 12:33 UTC, bobqianic commented
> > This is because I've set it to skip FFT calculations and output the results directly when the FFT input is all zeros during the calculation of log Mel.
> 
> How often do you observe this to be the case? I would guess it never happens for normal audio

After the log Mel correction, we should have `30` seconds of zeros, equating to `480,000` samples or approximately `2,998` frames. The presence of these zeros is due to the zero padding added to the end of the sample before performing calculations. With each FFT taking an estimated `25` microseconds, we anticipate a time saving of `75ms`. Additionally, by removing the if statement from the loop, we can reduce the number of branch predictions.

2023-08-25 12:43 UTC, bobqianic commented on whisper.cpp
> +        sin_vals[i] = sin(theta);
```suggestion
        sin_vals[i] = sinf(theta);
```

2023-08-25 12:47 UTC, bobqianic requested changes

2023-08-25 12:47 UTC, bobqianic commented on whisper.cpp
> +        cos_vals[i] = cos(theta);
```suggestion
        cos_vals[i] = cosf(theta);
```

2023-08-25 12:47 UTC, bobqianic commented on whisper.cpp
> +        sin_vals[i] = sin(theta);
```suggestion
        sin_vals[i] = sinf(theta);
```

2023-08-25 12:51 UTC, ggerganov approved these changes

2023-08-25 12:51 UTC, merged