Added whisper state + default state on the whisper_context
ggerganov/whisper.cpp pull request #523
Opened 2023-02-21 17:13 UTC by sandrohanea

2023-02-21 17:39 UTC, sandrohanea commented
Hey @ggerganov,
This PR is an alternative to https://github.com/ggerganov/whisper.cpp/pull/494 where the existing functionaliy is kept the same (by using a default_state) and additional capability (to run multiple transformations on the same context) is provided with newer functions.

Let me know what you think about this simpler approach.

If you'll like it, we can create some follow-up tasks to update emscripten + various samples to not create so many contexts anymore and save some memory. :)

2023-02-27 18:52 UTC, ggerganov requested changes
Nice - well done!

We need to update the callbacks in the examples.

> If you'll like it, we can create some follow-up tasks to update emscripten + various samples to not create so many contexts anymore and save some memory. :)

Hmm, where do we create many contexts?

2023-02-28 10:05 UTC, sandrohanea commented
> Nice - well done!
> 
> We need to update the callbacks in the examples.
> 
> > If you'll like it, we can create some follow-up tasks to update emscripten + various samples to not create so many contexts anymore and save some memory. :)
> 
> Hmm, where do we create many contexts?

Here for example: https://github.com/ggerganov/whisper.cpp/blob/master/examples/stream.wasm/emscripten.cpp#L16

But there are other samples which are creating multiple contexts like that.

2023-02-28 18:48 UTC, sandrohanea commented on whisper.cpp
> +    std::vector<uint8_t> buf_compute{};
Fixed all of them :)

2023-02-28 19:30 UTC, ggerganov commented on whisper.cpp
> +    void use_buf(struct ggml_context* ctx, int i) {
There is no auto formatter or any strict rules. I just arrange the code as I find it pleasing :)
Just try to follow the patterns

2023-02-28 19:32 UTC, ggerganov commented
@sandrohanea 
Ah, this looks like it creates multiple contexts, but in reality it is just one.
Initially I was thinking the WASM lib should support multiple contexts, so I created this global map. And then it propagated in various examples. But it is actually not needed. I should remove it and replace it with a single instance.

2023-03-05 19:42 UTC, merged